/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppWorkflowInboxRouteImport } from './routes/_app.workflow-inbox'
import { Route as AppWardRouteImport } from './routes/_app.ward'
import { Route as AppTriageRouteImport } from './routes/_app.triage'
import { Route as AppTheatreRouteImport } from './routes/_app.theatre'
import { Route as AppSystemHealthRouteImport } from './routes/_app.system-health'
import { Route as AppSupplierInvoicesRouteImport } from './routes/_app.supplier-invoices'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppServiceBusRouteImport } from './routes/_app.service-bus'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppReimbursementsRouteImport } from './routes/_app.reimbursements'
import { Route as AppPreadmissionsRouteImport } from './routes/_app.preadmissions'
import { Route as AppPractitionersRouteImport } from './routes/_app.practitioners'
import { Route as AppPharmacyRouteImport } from './routes/_app.pharmacy'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMylifePortalRouteImport } from './routes/_app.mylife-portal'
import { Route as AppMedicalEventsRouteImport } from './routes/_app.medical-events'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppFundingRouteImport } from './routes/_app.funding'
import { Route as AppFailedMessagesRouteImport } from './routes/_app.failed-messages'
import { Route as AppFacilitiesRouteImport } from './routes/_app.facilities'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppCoidRouteImport } from './routes/_app.coid'
import { Route as AppClinicalCodingRouteImport } from './routes/_app.clinical-coding'
import { Route as AppClinicalAssessmentsRouteImport } from './routes/_app.clinical-assessments'
import { Route as AppCaseManagementRouteImport } from './routes/_app.case-management'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAuthorisationsRouteImport } from './routes/_app.authorisations'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAdmissionsRouteImport } from './routes/_app.admissions'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAdhocRouteImport } from './routes/_app.adhoc'
import { Route as AppAccountingRouteImport } from './routes/_app.accounting'
import { Route as AppAccountEnquiriesRouteImport } from './routes/_app.account-enquiries'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppPharmacyIndexRouteImport } from './routes/_app.pharmacy.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppPharmacyWardTheatreRouteImport } from './routes/_app.pharmacy.ward-theatre'
import { Route as AppPharmacyRetailAccountsRouteImport } from './routes/_app.pharmacy.retail-accounts'
import { Route as AppPharmacyLabelsStockRouteImport } from './routes/_app.pharmacy.labels-stock'
import { Route as AppPharmacyEnquiryRouteImport } from './routes/_app.pharmacy.enquiry'
import { Route as AppPharmacyDispensingRouteImport } from './routes/_app.pharmacy.dispensing'
import { Route as AppPharmacyCompoundingRouteImport } from './routes/_app.pharmacy.compounding'
import { Route as AppPharmacyBusinessFlowRouteImport } from './routes/_app.pharmacy.business-flow'
import { Route as AppAdminWorkflowRouteImport } from './routes/_app.admin.workflow'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminSupportRouteImport } from './routes/_app.admin.support'
import { Route as AppAdminReferenceRouteImport } from './routes/_app.admin.reference'
import { Route as AppAdminPrintingRouteImport } from './routes/_app.admin.printing'
import { Route as AppAdminMonitoringRouteImport } from './routes/_app.admin.monitoring'
import { Route as AppAdminFeatureFlagsRouteImport } from './routes/_app.admin.feature-flags'
import { Route as AppAdminFacilitiesRouteImport } from './routes/_app.admin.facilities'
import { Route as AppAdminDocumentsRouteImport } from './routes/_app.admin.documents'
import { Route as AppAdminBillingRouteImport } from './routes/_app.admin.billing'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowInboxRoute = AppWorkflowInboxRouteImport.update({
  id: '/workflow-inbox',
  path: '/workflow-inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppWardRoute = AppWardRouteImport.update({
  id: '/ward',
  path: '/ward',
  getParentRoute: () => AppRoute,
} as any)
const AppTriageRoute = AppTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppRoute,
} as any)
const AppTheatreRoute = AppTheatreRouteImport.update({
  id: '/theatre',
  path: '/theatre',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemHealthRoute = AppSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AppRoute,
} as any)
const AppSupplierInvoicesRoute = AppSupplierInvoicesRouteImport.update({
  id: '/supplier-invoices',
  path: '/supplier-invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceBusRoute = AppServiceBusRouteImport.update({
  id: '/service-bus',
  path: '/service-bus',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReimbursementsRoute = AppReimbursementsRouteImport.update({
  id: '/reimbursements',
  path: '/reimbursements',
  getParentRoute: () => AppRoute,
} as any)
const AppPreadmissionsRoute = AppPreadmissionsRouteImport.update({
  id: '/preadmissions',
  path: '/preadmissions',
  getParentRoute: () => AppRoute,
} as any)
const AppPractitionersRoute = AppPractitionersRouteImport.update({
  id: '/practitioners',
  path: '/practitioners',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyRoute = AppPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMylifePortalRoute = AppMylifePortalRouteImport.update({
  id: '/mylife-portal',
  path: '/mylife-portal',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalEventsRoute = AppMedicalEventsRouteImport.update({
  id: '/medical-events',
  path: '/medical-events',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppFundingRoute = AppFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => AppRoute,
} as any)
const AppFailedMessagesRoute = AppFailedMessagesRouteImport.update({
  id: '/failed-messages',
  path: '/failed-messages',
  getParentRoute: () => AppRoute,
} as any)
const AppFacilitiesRoute = AppFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppCoidRoute = AppCoidRouteImport.update({
  id: '/coid',
  path: '/coid',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicalCodingRoute = AppClinicalCodingRouteImport.update({
  id: '/clinical-coding',
  path: '/clinical-coding',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicalAssessmentsRoute = AppClinicalAssessmentsRouteImport.update({
  id: '/clinical-assessments',
  path: '/clinical-assessments',
  getParentRoute: () => AppRoute,
} as any)
const AppCaseManagementRoute = AppCaseManagementRouteImport.update({
  id: '/case-management',
  path: '/case-management',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthorisationsRoute = AppAuthorisationsRouteImport.update({
  id: '/authorisations',
  path: '/authorisations',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmissionsRoute = AppAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdhocRoute = AppAdhocRouteImport.update({
  id: '/adhoc',
  path: '/adhoc',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountEnquiriesRoute = AppAccountEnquiriesRouteImport.update({
  id: '/account-enquiries',
  path: '/account-enquiries',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppPharmacyIndexRoute = AppPharmacyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPharmacyRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppPharmacyWardTheatreRoute = AppPharmacyWardTheatreRouteImport.update({
  id: '/ward-theatre',
  path: '/ward-theatre',
  getParentRoute: () => AppPharmacyRoute,
} as any)
const AppPharmacyRetailAccountsRoute =
  AppPharmacyRetailAccountsRouteImport.update({
    id: '/retail-accounts',
    path: '/retail-accounts',
    getParentRoute: () => AppPharmacyRoute,
  } as any)
const AppPharmacyLabelsStockRoute = AppPharmacyLabelsStockRouteImport.update({
  id: '/labels-stock',
  path: '/labels-stock',
  getParentRoute: () => AppPharmacyRoute,
} as any)
const AppPharmacyEnquiryRoute = AppPharmacyEnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => AppPharmacyRoute,
} as any)
const AppPharmacyDispensingRoute = AppPharmacyDispensingRouteImport.update({
  id: '/dispensing',
  path: '/dispensing',
  getParentRoute: () => AppPharmacyRoute,
} as any)
const AppPharmacyCompoundingRoute = AppPharmacyCompoundingRouteImport.update({
  id: '/compounding',
  path: '/compounding',
  getParentRoute: () => AppPharmacyRoute,
} as any)
const AppPharmacyBusinessFlowRoute = AppPharmacyBusinessFlowRouteImport.update({
  id: '/business-flow',
  path: '/business-flow',
  getParentRoute: () => AppPharmacyRoute,
} as any)
const AppAdminWorkflowRoute = AppAdminWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSupportRoute = AppAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReferenceRoute = AppAdminReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPrintingRoute = AppAdminPrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMonitoringRoute = AppAdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFeatureFlagsRoute = AppAdminFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFacilitiesRoute = AppAdminFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDocumentsRoute = AppAdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBillingRoute = AppAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppAdminRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account-enquiries': typeof AppAccountEnquiriesRoute
  '/accounting': typeof AppAccountingRoute
  '/adhoc': typeof AppAdhocRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/admissions': typeof AppAdmissionsRoute
  '/audit': typeof AppAuditRoute
  '/authorisations': typeof AppAuthorisationsRoute
  '/billing': typeof AppBillingRoute
  '/case-management': typeof AppCaseManagementRoute
  '/clinical-assessments': typeof AppClinicalAssessmentsRoute
  '/clinical-coding': typeof AppClinicalCodingRoute
  '/coid': typeof AppCoidRoute
  '/documents': typeof AppDocumentsRoute
  '/facilities': typeof AppFacilitiesRoute
  '/failed-messages': typeof AppFailedMessagesRoute
  '/funding': typeof AppFundingRoute
  '/integrations': typeof AppIntegrationsRoute
  '/medical-events': typeof AppMedicalEventsRoute
  '/mylife-portal': typeof AppMylifePortalRoute
  '/notifications': typeof AppNotificationsRoute
  '/patients': typeof AppPatientsRoute
  '/pharmacy': typeof AppPharmacyRouteWithChildren
  '/practitioners': typeof AppPractitionersRoute
  '/preadmissions': typeof AppPreadmissionsRoute
  '/reimbursements': typeof AppReimbursementsRoute
  '/reports': typeof AppReportsRoute
  '/service-bus': typeof AppServiceBusRoute
  '/services': typeof AppServicesRoute
  '/supplier-invoices': typeof AppSupplierInvoicesRoute
  '/system-health': typeof AppSystemHealthRoute
  '/theatre': typeof AppTheatreRoute
  '/triage': typeof AppTriageRoute
  '/ward': typeof AppWardRoute
  '/workflow-inbox': typeof AppWorkflowInboxRoute
  '/api/chat': typeof ApiChatRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/billing': typeof AppAdminBillingRoute
  '/admin/documents': typeof AppAdminDocumentsRoute
  '/admin/facilities': typeof AppAdminFacilitiesRoute
  '/admin/feature-flags': typeof AppAdminFeatureFlagsRoute
  '/admin/monitoring': typeof AppAdminMonitoringRoute
  '/admin/printing': typeof AppAdminPrintingRoute
  '/admin/reference': typeof AppAdminReferenceRoute
  '/admin/support': typeof AppAdminSupportRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/workflow': typeof AppAdminWorkflowRoute
  '/pharmacy/business-flow': typeof AppPharmacyBusinessFlowRoute
  '/pharmacy/compounding': typeof AppPharmacyCompoundingRoute
  '/pharmacy/dispensing': typeof AppPharmacyDispensingRoute
  '/pharmacy/enquiry': typeof AppPharmacyEnquiryRoute
  '/pharmacy/labels-stock': typeof AppPharmacyLabelsStockRoute
  '/pharmacy/retail-accounts': typeof AppPharmacyRetailAccountsRoute
  '/pharmacy/ward-theatre': typeof AppPharmacyWardTheatreRoute
  '/admin/': typeof AppAdminIndexRoute
  '/pharmacy/': typeof AppPharmacyIndexRoute
}
export interface FileRoutesByTo {
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account-enquiries': typeof AppAccountEnquiriesRoute
  '/accounting': typeof AppAccountingRoute
  '/adhoc': typeof AppAdhocRoute
  '/admissions': typeof AppAdmissionsRoute
  '/audit': typeof AppAuditRoute
  '/authorisations': typeof AppAuthorisationsRoute
  '/billing': typeof AppBillingRoute
  '/case-management': typeof AppCaseManagementRoute
  '/clinical-assessments': typeof AppClinicalAssessmentsRoute
  '/clinical-coding': typeof AppClinicalCodingRoute
  '/coid': typeof AppCoidRoute
  '/documents': typeof AppDocumentsRoute
  '/facilities': typeof AppFacilitiesRoute
  '/failed-messages': typeof AppFailedMessagesRoute
  '/funding': typeof AppFundingRoute
  '/integrations': typeof AppIntegrationsRoute
  '/medical-events': typeof AppMedicalEventsRoute
  '/mylife-portal': typeof AppMylifePortalRoute
  '/notifications': typeof AppNotificationsRoute
  '/patients': typeof AppPatientsRoute
  '/practitioners': typeof AppPractitionersRoute
  '/preadmissions': typeof AppPreadmissionsRoute
  '/reimbursements': typeof AppReimbursementsRoute
  '/reports': typeof AppReportsRoute
  '/service-bus': typeof AppServiceBusRoute
  '/services': typeof AppServicesRoute
  '/supplier-invoices': typeof AppSupplierInvoicesRoute
  '/system-health': typeof AppSystemHealthRoute
  '/theatre': typeof AppTheatreRoute
  '/triage': typeof AppTriageRoute
  '/ward': typeof AppWardRoute
  '/workflow-inbox': typeof AppWorkflowInboxRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/billing': typeof AppAdminBillingRoute
  '/admin/documents': typeof AppAdminDocumentsRoute
  '/admin/facilities': typeof AppAdminFacilitiesRoute
  '/admin/feature-flags': typeof AppAdminFeatureFlagsRoute
  '/admin/monitoring': typeof AppAdminMonitoringRoute
  '/admin/printing': typeof AppAdminPrintingRoute
  '/admin/reference': typeof AppAdminReferenceRoute
  '/admin/support': typeof AppAdminSupportRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/workflow': typeof AppAdminWorkflowRoute
  '/pharmacy/business-flow': typeof AppPharmacyBusinessFlowRoute
  '/pharmacy/compounding': typeof AppPharmacyCompoundingRoute
  '/pharmacy/dispensing': typeof AppPharmacyDispensingRoute
  '/pharmacy/enquiry': typeof AppPharmacyEnquiryRoute
  '/pharmacy/labels-stock': typeof AppPharmacyLabelsStockRoute
  '/pharmacy/retail-accounts': typeof AppPharmacyRetailAccountsRoute
  '/pharmacy/ward-theatre': typeof AppPharmacyWardTheatreRoute
  '/admin': typeof AppAdminIndexRoute
  '/pharmacy': typeof AppPharmacyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/account-enquiries': typeof AppAccountEnquiriesRoute
  '/_app/accounting': typeof AppAccountingRoute
  '/_app/adhoc': typeof AppAdhocRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/admissions': typeof AppAdmissionsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/authorisations': typeof AppAuthorisationsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/case-management': typeof AppCaseManagementRoute
  '/_app/clinical-assessments': typeof AppClinicalAssessmentsRoute
  '/_app/clinical-coding': typeof AppClinicalCodingRoute
  '/_app/coid': typeof AppCoidRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/facilities': typeof AppFacilitiesRoute
  '/_app/failed-messages': typeof AppFailedMessagesRoute
  '/_app/funding': typeof AppFundingRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/medical-events': typeof AppMedicalEventsRoute
  '/_app/mylife-portal': typeof AppMylifePortalRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/pharmacy': typeof AppPharmacyRouteWithChildren
  '/_app/practitioners': typeof AppPractitionersRoute
  '/_app/preadmissions': typeof AppPreadmissionsRoute
  '/_app/reimbursements': typeof AppReimbursementsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/service-bus': typeof AppServiceBusRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/supplier-invoices': typeof AppSupplierInvoicesRoute
  '/_app/system-health': typeof AppSystemHealthRoute
  '/_app/theatre': typeof AppTheatreRoute
  '/_app/triage': typeof AppTriageRoute
  '/_app/ward': typeof AppWardRoute
  '/_app/workflow-inbox': typeof AppWorkflowInboxRoute
  '/api/chat': typeof ApiChatRoute
  '/_app/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/admin/billing': typeof AppAdminBillingRoute
  '/_app/admin/documents': typeof AppAdminDocumentsRoute
  '/_app/admin/facilities': typeof AppAdminFacilitiesRoute
  '/_app/admin/feature-flags': typeof AppAdminFeatureFlagsRoute
  '/_app/admin/monitoring': typeof AppAdminMonitoringRoute
  '/_app/admin/printing': typeof AppAdminPrintingRoute
  '/_app/admin/reference': typeof AppAdminReferenceRoute
  '/_app/admin/support': typeof AppAdminSupportRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/workflow': typeof AppAdminWorkflowRoute
  '/_app/pharmacy/business-flow': typeof AppPharmacyBusinessFlowRoute
  '/_app/pharmacy/compounding': typeof AppPharmacyCompoundingRoute
  '/_app/pharmacy/dispensing': typeof AppPharmacyDispensingRoute
  '/_app/pharmacy/enquiry': typeof AppPharmacyEnquiryRoute
  '/_app/pharmacy/labels-stock': typeof AppPharmacyLabelsStockRoute
  '/_app/pharmacy/retail-accounts': typeof AppPharmacyRetailAccountsRoute
  '/_app/pharmacy/ward-theatre': typeof AppPharmacyWardTheatreRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/pharmacy/': typeof AppPharmacyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account-enquiries'
    | '/accounting'
    | '/adhoc'
    | '/admin'
    | '/admissions'
    | '/audit'
    | '/authorisations'
    | '/billing'
    | '/case-management'
    | '/clinical-assessments'
    | '/clinical-coding'
    | '/coid'
    | '/documents'
    | '/facilities'
    | '/failed-messages'
    | '/funding'
    | '/integrations'
    | '/medical-events'
    | '/mylife-portal'
    | '/notifications'
    | '/patients'
    | '/pharmacy'
    | '/practitioners'
    | '/preadmissions'
    | '/reimbursements'
    | '/reports'
    | '/service-bus'
    | '/services'
    | '/supplier-invoices'
    | '/system-health'
    | '/theatre'
    | '/triage'
    | '/ward'
    | '/workflow-inbox'
    | '/api/chat'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/billing'
    | '/admin/documents'
    | '/admin/facilities'
    | '/admin/feature-flags'
    | '/admin/monitoring'
    | '/admin/printing'
    | '/admin/reference'
    | '/admin/support'
    | '/admin/users'
    | '/admin/workflow'
    | '/pharmacy/business-flow'
    | '/pharmacy/compounding'
    | '/pharmacy/dispensing'
    | '/pharmacy/enquiry'
    | '/pharmacy/labels-stock'
    | '/pharmacy/retail-accounts'
    | '/pharmacy/ward-theatre'
    | '/admin/'
    | '/pharmacy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account-enquiries'
    | '/accounting'
    | '/adhoc'
    | '/admissions'
    | '/audit'
    | '/authorisations'
    | '/billing'
    | '/case-management'
    | '/clinical-assessments'
    | '/clinical-coding'
    | '/coid'
    | '/documents'
    | '/facilities'
    | '/failed-messages'
    | '/funding'
    | '/integrations'
    | '/medical-events'
    | '/mylife-portal'
    | '/notifications'
    | '/patients'
    | '/practitioners'
    | '/preadmissions'
    | '/reimbursements'
    | '/reports'
    | '/service-bus'
    | '/services'
    | '/supplier-invoices'
    | '/system-health'
    | '/theatre'
    | '/triage'
    | '/ward'
    | '/workflow-inbox'
    | '/api/chat'
    | '/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/billing'
    | '/admin/documents'
    | '/admin/facilities'
    | '/admin/feature-flags'
    | '/admin/monitoring'
    | '/admin/printing'
    | '/admin/reference'
    | '/admin/support'
    | '/admin/users'
    | '/admin/workflow'
    | '/pharmacy/business-flow'
    | '/pharmacy/compounding'
    | '/pharmacy/dispensing'
    | '/pharmacy/enquiry'
    | '/pharmacy/labels-stock'
    | '/pharmacy/retail-accounts'
    | '/pharmacy/ward-theatre'
    | '/admin'
    | '/pharmacy'
  id:
    | '__root__'
    | '/_app'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/account-enquiries'
    | '/_app/accounting'
    | '/_app/adhoc'
    | '/_app/admin'
    | '/_app/admissions'
    | '/_app/audit'
    | '/_app/authorisations'
    | '/_app/billing'
    | '/_app/case-management'
    | '/_app/clinical-assessments'
    | '/_app/clinical-coding'
    | '/_app/coid'
    | '/_app/documents'
    | '/_app/facilities'
    | '/_app/failed-messages'
    | '/_app/funding'
    | '/_app/integrations'
    | '/_app/medical-events'
    | '/_app/mylife-portal'
    | '/_app/notifications'
    | '/_app/patients'
    | '/_app/pharmacy'
    | '/_app/practitioners'
    | '/_app/preadmissions'
    | '/_app/reimbursements'
    | '/_app/reports'
    | '/_app/service-bus'
    | '/_app/services'
    | '/_app/supplier-invoices'
    | '/_app/system-health'
    | '/_app/theatre'
    | '/_app/triage'
    | '/_app/ward'
    | '/_app/workflow-inbox'
    | '/api/chat'
    | '/_app/'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/admin/billing'
    | '/_app/admin/documents'
    | '/_app/admin/facilities'
    | '/_app/admin/feature-flags'
    | '/_app/admin/monitoring'
    | '/_app/admin/printing'
    | '/_app/admin/reference'
    | '/_app/admin/support'
    | '/_app/admin/users'
    | '/_app/admin/workflow'
    | '/_app/pharmacy/business-flow'
    | '/_app/pharmacy/compounding'
    | '/_app/pharmacy/dispensing'
    | '/_app/pharmacy/enquiry'
    | '/_app/pharmacy/labels-stock'
    | '/_app/pharmacy/retail-accounts'
    | '/_app/pharmacy/ward-theatre'
    | '/_app/admin/'
    | '/_app/pharmacy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflow-inbox': {
      id: '/_app/workflow-inbox'
      path: '/workflow-inbox'
      fullPath: '/workflow-inbox'
      preLoaderRoute: typeof AppWorkflowInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ward': {
      id: '/_app/ward'
      path: '/ward'
      fullPath: '/ward'
      preLoaderRoute: typeof AppWardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triage': {
      id: '/_app/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof AppTriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/theatre': {
      id: '/_app/theatre'
      path: '/theatre'
      fullPath: '/theatre'
      preLoaderRoute: typeof AppTheatreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system-health': {
      id: '/_app/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof AppSystemHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supplier-invoices': {
      id: '/_app/supplier-invoices'
      path: '/supplier-invoices'
      fullPath: '/supplier-invoices'
      preLoaderRoute: typeof AppSupplierInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service-bus': {
      id: '/_app/service-bus'
      path: '/service-bus'
      fullPath: '/service-bus'
      preLoaderRoute: typeof AppServiceBusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reimbursements': {
      id: '/_app/reimbursements'
      path: '/reimbursements'
      fullPath: '/reimbursements'
      preLoaderRoute: typeof AppReimbursementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preadmissions': {
      id: '/_app/preadmissions'
      path: '/preadmissions'
      fullPath: '/preadmissions'
      preLoaderRoute: typeof AppPreadmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practitioners': {
      id: '/_app/practitioners'
      path: '/practitioners'
      fullPath: '/practitioners'
      preLoaderRoute: typeof AppPractitionersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pharmacy': {
      id: '/_app/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AppPharmacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mylife-portal': {
      id: '/_app/mylife-portal'
      path: '/mylife-portal'
      fullPath: '/mylife-portal'
      preLoaderRoute: typeof AppMylifePortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical-events': {
      id: '/_app/medical-events'
      path: '/medical-events'
      fullPath: '/medical-events'
      preLoaderRoute: typeof AppMedicalEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funding': {
      id: '/_app/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof AppFundingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/failed-messages': {
      id: '/_app/failed-messages'
      path: '/failed-messages'
      fullPath: '/failed-messages'
      preLoaderRoute: typeof AppFailedMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facilities': {
      id: '/_app/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AppFacilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coid': {
      id: '/_app/coid'
      path: '/coid'
      fullPath: '/coid'
      preLoaderRoute: typeof AppCoidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clinical-coding': {
      id: '/_app/clinical-coding'
      path: '/clinical-coding'
      fullPath: '/clinical-coding'
      preLoaderRoute: typeof AppClinicalCodingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clinical-assessments': {
      id: '/_app/clinical-assessments'
      path: '/clinical-assessments'
      fullPath: '/clinical-assessments'
      preLoaderRoute: typeof AppClinicalAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-management': {
      id: '/_app/case-management'
      path: '/case-management'
      fullPath: '/case-management'
      preLoaderRoute: typeof AppCaseManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorisations': {
      id: '/_app/authorisations'
      path: '/authorisations'
      fullPath: '/authorisations'
      preLoaderRoute: typeof AppAuthorisationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admissions': {
      id: '/_app/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AppAdmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/adhoc': {
      id: '/_app/adhoc'
      path: '/adhoc'
      fullPath: '/adhoc'
      preLoaderRoute: typeof AppAdhocRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account-enquiries': {
      id: '/_app/account-enquiries'
      path: '/account-enquiries'
      fullPath: '/account-enquiries'
      preLoaderRoute: typeof AppAccountEnquiriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pharmacy/': {
      id: '/_app/pharmacy/'
      path: '/'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof AppPharmacyIndexRouteImport
      parentRoute: typeof AppPharmacyRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/pharmacy/ward-theatre': {
      id: '/_app/pharmacy/ward-theatre'
      path: '/ward-theatre'
      fullPath: '/pharmacy/ward-theatre'
      preLoaderRoute: typeof AppPharmacyWardTheatreRouteImport
      parentRoute: typeof AppPharmacyRoute
    }
    '/_app/pharmacy/retail-accounts': {
      id: '/_app/pharmacy/retail-accounts'
      path: '/retail-accounts'
      fullPath: '/pharmacy/retail-accounts'
      preLoaderRoute: typeof AppPharmacyRetailAccountsRouteImport
      parentRoute: typeof AppPharmacyRoute
    }
    '/_app/pharmacy/labels-stock': {
      id: '/_app/pharmacy/labels-stock'
      path: '/labels-stock'
      fullPath: '/pharmacy/labels-stock'
      preLoaderRoute: typeof AppPharmacyLabelsStockRouteImport
      parentRoute: typeof AppPharmacyRoute
    }
    '/_app/pharmacy/enquiry': {
      id: '/_app/pharmacy/enquiry'
      path: '/enquiry'
      fullPath: '/pharmacy/enquiry'
      preLoaderRoute: typeof AppPharmacyEnquiryRouteImport
      parentRoute: typeof AppPharmacyRoute
    }
    '/_app/pharmacy/dispensing': {
      id: '/_app/pharmacy/dispensing'
      path: '/dispensing'
      fullPath: '/pharmacy/dispensing'
      preLoaderRoute: typeof AppPharmacyDispensingRouteImport
      parentRoute: typeof AppPharmacyRoute
    }
    '/_app/pharmacy/compounding': {
      id: '/_app/pharmacy/compounding'
      path: '/compounding'
      fullPath: '/pharmacy/compounding'
      preLoaderRoute: typeof AppPharmacyCompoundingRouteImport
      parentRoute: typeof AppPharmacyRoute
    }
    '/_app/pharmacy/business-flow': {
      id: '/_app/pharmacy/business-flow'
      path: '/business-flow'
      fullPath: '/pharmacy/business-flow'
      preLoaderRoute: typeof AppPharmacyBusinessFlowRouteImport
      parentRoute: typeof AppPharmacyRoute
    }
    '/_app/admin/workflow': {
      id: '/_app/admin/workflow'
      path: '/workflow'
      fullPath: '/admin/workflow'
      preLoaderRoute: typeof AppAdminWorkflowRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/support': {
      id: '/_app/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AppAdminSupportRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/reference': {
      id: '/_app/admin/reference'
      path: '/reference'
      fullPath: '/admin/reference'
      preLoaderRoute: typeof AppAdminReferenceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/printing': {
      id: '/_app/admin/printing'
      path: '/printing'
      fullPath: '/admin/printing'
      preLoaderRoute: typeof AppAdminPrintingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/monitoring': {
      id: '/_app/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AppAdminMonitoringRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/feature-flags': {
      id: '/_app/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AppAdminFeatureFlagsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/facilities': {
      id: '/_app/admin/facilities'
      path: '/facilities'
      fullPath: '/admin/facilities'
      preLoaderRoute: typeof AppAdminFacilitiesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/documents': {
      id: '/_app/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AppAdminDocumentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/billing': {
      id: '/_app/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AppAdminBillingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminBillingRoute: typeof AppAdminBillingRoute
  AppAdminDocumentsRoute: typeof AppAdminDocumentsRoute
  AppAdminFacilitiesRoute: typeof AppAdminFacilitiesRoute
  AppAdminFeatureFlagsRoute: typeof AppAdminFeatureFlagsRoute
  AppAdminMonitoringRoute: typeof AppAdminMonitoringRoute
  AppAdminPrintingRoute: typeof AppAdminPrintingRoute
  AppAdminReferenceRoute: typeof AppAdminReferenceRoute
  AppAdminSupportRoute: typeof AppAdminSupportRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminWorkflowRoute: typeof AppAdminWorkflowRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminBillingRoute: AppAdminBillingRoute,
  AppAdminDocumentsRoute: AppAdminDocumentsRoute,
  AppAdminFacilitiesRoute: AppAdminFacilitiesRoute,
  AppAdminFeatureFlagsRoute: AppAdminFeatureFlagsRoute,
  AppAdminMonitoringRoute: AppAdminMonitoringRoute,
  AppAdminPrintingRoute: AppAdminPrintingRoute,
  AppAdminReferenceRoute: AppAdminReferenceRoute,
  AppAdminSupportRoute: AppAdminSupportRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminWorkflowRoute: AppAdminWorkflowRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppPharmacyRouteChildren {
  AppPharmacyBusinessFlowRoute: typeof AppPharmacyBusinessFlowRoute
  AppPharmacyCompoundingRoute: typeof AppPharmacyCompoundingRoute
  AppPharmacyDispensingRoute: typeof AppPharmacyDispensingRoute
  AppPharmacyEnquiryRoute: typeof AppPharmacyEnquiryRoute
  AppPharmacyLabelsStockRoute: typeof AppPharmacyLabelsStockRoute
  AppPharmacyRetailAccountsRoute: typeof AppPharmacyRetailAccountsRoute
  AppPharmacyWardTheatreRoute: typeof AppPharmacyWardTheatreRoute
  AppPharmacyIndexRoute: typeof AppPharmacyIndexRoute
}

const AppPharmacyRouteChildren: AppPharmacyRouteChildren = {
  AppPharmacyBusinessFlowRoute: AppPharmacyBusinessFlowRoute,
  AppPharmacyCompoundingRoute: AppPharmacyCompoundingRoute,
  AppPharmacyDispensingRoute: AppPharmacyDispensingRoute,
  AppPharmacyEnquiryRoute: AppPharmacyEnquiryRoute,
  AppPharmacyLabelsStockRoute: AppPharmacyLabelsStockRoute,
  AppPharmacyRetailAccountsRoute: AppPharmacyRetailAccountsRoute,
  AppPharmacyWardTheatreRoute: AppPharmacyWardTheatreRoute,
  AppPharmacyIndexRoute: AppPharmacyIndexRoute,
}

const AppPharmacyRouteWithChildren = AppPharmacyRoute._addFileChildren(
  AppPharmacyRouteChildren,
)

interface AppRouteChildren {
  AppAccountEnquiriesRoute: typeof AppAccountEnquiriesRoute
  AppAccountingRoute: typeof AppAccountingRoute
  AppAdhocRoute: typeof AppAdhocRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAdmissionsRoute: typeof AppAdmissionsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppAuthorisationsRoute: typeof AppAuthorisationsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCaseManagementRoute: typeof AppCaseManagementRoute
  AppClinicalAssessmentsRoute: typeof AppClinicalAssessmentsRoute
  AppClinicalCodingRoute: typeof AppClinicalCodingRoute
  AppCoidRoute: typeof AppCoidRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFacilitiesRoute: typeof AppFacilitiesRoute
  AppFailedMessagesRoute: typeof AppFailedMessagesRoute
  AppFundingRoute: typeof AppFundingRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppMedicalEventsRoute: typeof AppMedicalEventsRoute
  AppMylifePortalRoute: typeof AppMylifePortalRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPharmacyRoute: typeof AppPharmacyRouteWithChildren
  AppPractitionersRoute: typeof AppPractitionersRoute
  AppPreadmissionsRoute: typeof AppPreadmissionsRoute
  AppReimbursementsRoute: typeof AppReimbursementsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppServiceBusRoute: typeof AppServiceBusRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSupplierInvoicesRoute: typeof AppSupplierInvoicesRoute
  AppSystemHealthRoute: typeof AppSystemHealthRoute
  AppTheatreRoute: typeof AppTheatreRoute
  AppTriageRoute: typeof AppTriageRoute
  AppWardRoute: typeof AppWardRoute
  AppWorkflowInboxRoute: typeof AppWorkflowInboxRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountEnquiriesRoute: AppAccountEnquiriesRoute,
  AppAccountingRoute: AppAccountingRoute,
  AppAdhocRoute: AppAdhocRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAdmissionsRoute: AppAdmissionsRoute,
  AppAuditRoute: AppAuditRoute,
  AppAuthorisationsRoute: AppAuthorisationsRoute,
  AppBillingRoute: AppBillingRoute,
  AppCaseManagementRoute: AppCaseManagementRoute,
  AppClinicalAssessmentsRoute: AppClinicalAssessmentsRoute,
  AppClinicalCodingRoute: AppClinicalCodingRoute,
  AppCoidRoute: AppCoidRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFacilitiesRoute: AppFacilitiesRoute,
  AppFailedMessagesRoute: AppFailedMessagesRoute,
  AppFundingRoute: AppFundingRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppMedicalEventsRoute: AppMedicalEventsRoute,
  AppMylifePortalRoute: AppMylifePortalRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPharmacyRoute: AppPharmacyRouteWithChildren,
  AppPractitionersRoute: AppPractitionersRoute,
  AppPreadmissionsRoute: AppPreadmissionsRoute,
  AppReimbursementsRoute: AppReimbursementsRoute,
  AppReportsRoute: AppReportsRoute,
  AppServiceBusRoute: AppServiceBusRoute,
  AppServicesRoute: AppServicesRoute,
  AppSupplierInvoicesRoute: AppSupplierInvoicesRoute,
  AppSystemHealthRoute: AppSystemHealthRoute,
  AppTheatreRoute: AppTheatreRoute,
  AppTriageRoute: AppTriageRoute,
  AppWardRoute: AppWardRoute,
  AppWorkflowInboxRoute: AppWorkflowInboxRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
