/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppWardRouteImport } from './routes/_app.ward'
import { Route as AppTriangleRouteImport } from './routes/_app.triangle'
import { Route as AppTheatreRouteImport } from './routes/_app.theatre'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPreadmissionsRouteImport } from './routes/_app.preadmissions'
import { Route as AppPractitionersRouteImport } from './routes/_app.practitioners'
import { Route as AppPharmacyRouteImport } from './routes/_app.pharmacy'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppFundingRouteImport } from './routes/_app.funding'
import { Route as AppFacilitiesRouteImport } from './routes/_app.facilities'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppCoidRouteImport } from './routes/_app.coid'
import { Route as AppCaseManagementRouteImport } from './routes/_app.case-management'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAuthorisationsRouteImport } from './routes/_app.authorisations'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAdmissionsRouteImport } from './routes/_app.admissions'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAdhocRouteImport } from './routes/_app.adhoc'
import { Route as AppAccountingRouteImport } from './routes/_app.accounting'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminReferenceRouteImport } from './routes/_app.admin.reference'
import { Route as AppAdminPrintingRouteImport } from './routes/_app.admin.printing'
import { Route as AppAdminMonitoringRouteImport } from './routes/_app.admin.monitoring'
import { Route as AppAdminFacilitiesRouteImport } from './routes/_app.admin.facilities'
import { Route as AppAdminBillingRouteImport } from './routes/_app.admin.billing'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWardRoute = AppWardRouteImport.update({
  id: '/ward',
  path: '/ward',
  getParentRoute: () => AppRoute,
} as any)
const AppTriangleRoute = AppTriangleRouteImport.update({
  id: '/triangle',
  path: '/triangle',
  getParentRoute: () => AppRoute,
} as any)
const AppTheatreRoute = AppTheatreRouteImport.update({
  id: '/theatre',
  path: '/theatre',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPreadmissionsRoute = AppPreadmissionsRouteImport.update({
  id: '/preadmissions',
  path: '/preadmissions',
  getParentRoute: () => AppRoute,
} as any)
const AppPractitionersRoute = AppPractitionersRouteImport.update({
  id: '/practitioners',
  path: '/practitioners',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyRoute = AppPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppFundingRoute = AppFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => AppRoute,
} as any)
const AppFacilitiesRoute = AppFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppCoidRoute = AppCoidRouteImport.update({
  id: '/coid',
  path: '/coid',
  getParentRoute: () => AppRoute,
} as any)
const AppCaseManagementRoute = AppCaseManagementRouteImport.update({
  id: '/case-management',
  path: '/case-management',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthorisationsRoute = AppAuthorisationsRouteImport.update({
  id: '/authorisations',
  path: '/authorisations',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmissionsRoute = AppAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdhocRoute = AppAdhocRouteImport.update({
  id: '/adhoc',
  path: '/adhoc',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReferenceRoute = AppAdminReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPrintingRoute = AppAdminPrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMonitoringRoute = AppAdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFacilitiesRoute = AppAdminFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBillingRoute = AppAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppAdminRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accounting': typeof AppAccountingRoute
  '/adhoc': typeof AppAdhocRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/admissions': typeof AppAdmissionsRoute
  '/audit': typeof AppAuditRoute
  '/authorisations': typeof AppAuthorisationsRoute
  '/billing': typeof AppBillingRoute
  '/case-management': typeof AppCaseManagementRoute
  '/coid': typeof AppCoidRoute
  '/documents': typeof AppDocumentsRoute
  '/facilities': typeof AppFacilitiesRoute
  '/funding': typeof AppFundingRoute
  '/integrations': typeof AppIntegrationsRoute
  '/patients': typeof AppPatientsRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/practitioners': typeof AppPractitionersRoute
  '/preadmissions': typeof AppPreadmissionsRoute
  '/reports': typeof AppReportsRoute
  '/theatre': typeof AppTheatreRoute
  '/triangle': typeof AppTriangleRoute
  '/ward': typeof AppWardRoute
  '/api/chat': typeof ApiChatRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/billing': typeof AppAdminBillingRoute
  '/admin/facilities': typeof AppAdminFacilitiesRoute
  '/admin/monitoring': typeof AppAdminMonitoringRoute
  '/admin/printing': typeof AppAdminPrintingRoute
  '/admin/reference': typeof AppAdminReferenceRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accounting': typeof AppAccountingRoute
  '/adhoc': typeof AppAdhocRoute
  '/admissions': typeof AppAdmissionsRoute
  '/audit': typeof AppAuditRoute
  '/authorisations': typeof AppAuthorisationsRoute
  '/billing': typeof AppBillingRoute
  '/case-management': typeof AppCaseManagementRoute
  '/coid': typeof AppCoidRoute
  '/documents': typeof AppDocumentsRoute
  '/facilities': typeof AppFacilitiesRoute
  '/funding': typeof AppFundingRoute
  '/integrations': typeof AppIntegrationsRoute
  '/patients': typeof AppPatientsRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/practitioners': typeof AppPractitionersRoute
  '/preadmissions': typeof AppPreadmissionsRoute
  '/reports': typeof AppReportsRoute
  '/theatre': typeof AppTheatreRoute
  '/triangle': typeof AppTriangleRoute
  '/ward': typeof AppWardRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/billing': typeof AppAdminBillingRoute
  '/admin/facilities': typeof AppAdminFacilitiesRoute
  '/admin/monitoring': typeof AppAdminMonitoringRoute
  '/admin/printing': typeof AppAdminPrintingRoute
  '/admin/reference': typeof AppAdminReferenceRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/accounting': typeof AppAccountingRoute
  '/_app/adhoc': typeof AppAdhocRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/admissions': typeof AppAdmissionsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/authorisations': typeof AppAuthorisationsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/case-management': typeof AppCaseManagementRoute
  '/_app/coid': typeof AppCoidRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/facilities': typeof AppFacilitiesRoute
  '/_app/funding': typeof AppFundingRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/pharmacy': typeof AppPharmacyRoute
  '/_app/practitioners': typeof AppPractitionersRoute
  '/_app/preadmissions': typeof AppPreadmissionsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/theatre': typeof AppTheatreRoute
  '/_app/triangle': typeof AppTriangleRoute
  '/_app/ward': typeof AppWardRoute
  '/api/chat': typeof ApiChatRoute
  '/_app/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/admin/billing': typeof AppAdminBillingRoute
  '/_app/admin/facilities': typeof AppAdminFacilitiesRoute
  '/_app/admin/monitoring': typeof AppAdminMonitoringRoute
  '/_app/admin/printing': typeof AppAdminPrintingRoute
  '/_app/admin/reference': typeof AppAdminReferenceRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accounting'
    | '/adhoc'
    | '/admin'
    | '/admissions'
    | '/audit'
    | '/authorisations'
    | '/billing'
    | '/case-management'
    | '/coid'
    | '/documents'
    | '/facilities'
    | '/funding'
    | '/integrations'
    | '/patients'
    | '/pharmacy'
    | '/practitioners'
    | '/preadmissions'
    | '/reports'
    | '/theatre'
    | '/triangle'
    | '/ward'
    | '/api/chat'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/billing'
    | '/admin/facilities'
    | '/admin/monitoring'
    | '/admin/printing'
    | '/admin/reference'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accounting'
    | '/adhoc'
    | '/admissions'
    | '/audit'
    | '/authorisations'
    | '/billing'
    | '/case-management'
    | '/coid'
    | '/documents'
    | '/facilities'
    | '/funding'
    | '/integrations'
    | '/patients'
    | '/pharmacy'
    | '/practitioners'
    | '/preadmissions'
    | '/reports'
    | '/theatre'
    | '/triangle'
    | '/ward'
    | '/api/chat'
    | '/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/billing'
    | '/admin/facilities'
    | '/admin/monitoring'
    | '/admin/printing'
    | '/admin/reference'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/_app'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/accounting'
    | '/_app/adhoc'
    | '/_app/admin'
    | '/_app/admissions'
    | '/_app/audit'
    | '/_app/authorisations'
    | '/_app/billing'
    | '/_app/case-management'
    | '/_app/coid'
    | '/_app/documents'
    | '/_app/facilities'
    | '/_app/funding'
    | '/_app/integrations'
    | '/_app/patients'
    | '/_app/pharmacy'
    | '/_app/practitioners'
    | '/_app/preadmissions'
    | '/_app/reports'
    | '/_app/theatre'
    | '/_app/triangle'
    | '/_app/ward'
    | '/api/chat'
    | '/_app/'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/admin/billing'
    | '/_app/admin/facilities'
    | '/_app/admin/monitoring'
    | '/_app/admin/printing'
    | '/_app/admin/reference'
    | '/_app/admin/users'
    | '/_app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ward': {
      id: '/_app/ward'
      path: '/ward'
      fullPath: '/ward'
      preLoaderRoute: typeof AppWardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triangle': {
      id: '/_app/triangle'
      path: '/triangle'
      fullPath: '/triangle'
      preLoaderRoute: typeof AppTriangleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/theatre': {
      id: '/_app/theatre'
      path: '/theatre'
      fullPath: '/theatre'
      preLoaderRoute: typeof AppTheatreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preadmissions': {
      id: '/_app/preadmissions'
      path: '/preadmissions'
      fullPath: '/preadmissions'
      preLoaderRoute: typeof AppPreadmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practitioners': {
      id: '/_app/practitioners'
      path: '/practitioners'
      fullPath: '/practitioners'
      preLoaderRoute: typeof AppPractitionersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pharmacy': {
      id: '/_app/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AppPharmacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funding': {
      id: '/_app/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof AppFundingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facilities': {
      id: '/_app/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AppFacilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coid': {
      id: '/_app/coid'
      path: '/coid'
      fullPath: '/coid'
      preLoaderRoute: typeof AppCoidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-management': {
      id: '/_app/case-management'
      path: '/case-management'
      fullPath: '/case-management'
      preLoaderRoute: typeof AppCaseManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authorisations': {
      id: '/_app/authorisations'
      path: '/authorisations'
      fullPath: '/authorisations'
      preLoaderRoute: typeof AppAuthorisationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admissions': {
      id: '/_app/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AppAdmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/adhoc': {
      id: '/_app/adhoc'
      path: '/adhoc'
      fullPath: '/adhoc'
      preLoaderRoute: typeof AppAdhocRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/reference': {
      id: '/_app/admin/reference'
      path: '/reference'
      fullPath: '/admin/reference'
      preLoaderRoute: typeof AppAdminReferenceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/printing': {
      id: '/_app/admin/printing'
      path: '/printing'
      fullPath: '/admin/printing'
      preLoaderRoute: typeof AppAdminPrintingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/monitoring': {
      id: '/_app/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AppAdminMonitoringRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/facilities': {
      id: '/_app/admin/facilities'
      path: '/facilities'
      fullPath: '/admin/facilities'
      preLoaderRoute: typeof AppAdminFacilitiesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/billing': {
      id: '/_app/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AppAdminBillingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminBillingRoute: typeof AppAdminBillingRoute
  AppAdminFacilitiesRoute: typeof AppAdminFacilitiesRoute
  AppAdminMonitoringRoute: typeof AppAdminMonitoringRoute
  AppAdminPrintingRoute: typeof AppAdminPrintingRoute
  AppAdminReferenceRoute: typeof AppAdminReferenceRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminBillingRoute: AppAdminBillingRoute,
  AppAdminFacilitiesRoute: AppAdminFacilitiesRoute,
  AppAdminMonitoringRoute: AppAdminMonitoringRoute,
  AppAdminPrintingRoute: AppAdminPrintingRoute,
  AppAdminReferenceRoute: AppAdminReferenceRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppAdhocRoute: typeof AppAdhocRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAdmissionsRoute: typeof AppAdmissionsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppAuthorisationsRoute: typeof AppAuthorisationsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCaseManagementRoute: typeof AppCaseManagementRoute
  AppCoidRoute: typeof AppCoidRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFacilitiesRoute: typeof AppFacilitiesRoute
  AppFundingRoute: typeof AppFundingRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPharmacyRoute: typeof AppPharmacyRoute
  AppPractitionersRoute: typeof AppPractitionersRoute
  AppPreadmissionsRoute: typeof AppPreadmissionsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTheatreRoute: typeof AppTheatreRoute
  AppTriangleRoute: typeof AppTriangleRoute
  AppWardRoute: typeof AppWardRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppAdhocRoute: AppAdhocRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAdmissionsRoute: AppAdmissionsRoute,
  AppAuditRoute: AppAuditRoute,
  AppAuthorisationsRoute: AppAuthorisationsRoute,
  AppBillingRoute: AppBillingRoute,
  AppCaseManagementRoute: AppCaseManagementRoute,
  AppCoidRoute: AppCoidRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFacilitiesRoute: AppFacilitiesRoute,
  AppFundingRoute: AppFundingRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPharmacyRoute: AppPharmacyRoute,
  AppPractitionersRoute: AppPractitionersRoute,
  AppPreadmissionsRoute: AppPreadmissionsRoute,
  AppReportsRoute: AppReportsRoute,
  AppTheatreRoute: AppTheatreRoute,
  AppTriangleRoute: AppTriangleRoute,
  AppWardRoute: AppWardRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
